name: Actions Worlflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: cheeckout
        uses: actions/checkout@v3
      - name: List files after checkout
        run: |
          pwd
          ls -a
      - name: Simple javascript Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Noor"
      - name: Log greeted time
        run: echo "${{steps.greet.outputs.time}}"
