name: matrix
# we just changed it to pull so that it does not run everytime we push when testing out other workflows
on: pull
jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6, 7, 8, 9, 10]
        exclude:
          - os: ubuntu-latest
            node-version: 6
      fail-fast: true
      # max-parallel: 2
    runs-on: ${{matrix.os}}
    steps:
      - name: Log Node node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log Node Version Again
        run: node -v
